# Generated by Django 4.1.5 on 2023-01-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamGovtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeId', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('solicitationNumber', models.IntegerField()),
                ('fullParentPathName', models.CharField(max_length=500)),
                ('fullParentPathCode', models.IntegerField()),
                ('postedDate', models.DateField()),
                ('archiveDate', models.DateField()),
                ('typeOfSetAsideDescription', models.CharField(max_length=500)),
                ('typeOfSetAside', models.CharField(max_length=80)),
                ('responseDeadLine', models.DateField()),
                ('naicsCode', models.IntegerField()),
                ('classificationCode', models.IntegerField()),
                ('active', models.CharField(max_length=80)),
                ('award', models.CharField(max_length=80)),
                ('fax', models.IntegerField()),
                ('type', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=32)),
                ('phone', models.IntegerField()),
                ('fullName', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('organizationType', models.CharField(max_length=500)),
                ('officeAddress', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('countryCode', models.IntegerField()),
                ('state', models.CharField(max_length=300)),
                ('placeOfPerformance', models.CharField(max_length=300)),
                ('additionalInfoLink', models.URLField()),
                ('uiLink', models.URLField()),
                ('resourceLinks', models.URLField()),
            ],
        ),
    ]
