# Generated by Django 4.1.5 on 2023-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samgovtdata',
            old_name='resourceLinks',
            new_name='links',
        ),
        migrations.RemoveField(
            model_name='samgovtdata',
            name='officeAddress',
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='additionalInfoLink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='placeOfPerformance',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
