# Generated by Django 4.1.5 on 2023-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_resourcelinks_samgovtdata_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samgovtdata',
            name='countryCode',
            field=models.CharField(max_length=20),
        ),
    ]
