# Generated by Django 4.1.5 on 2023-01-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_samgovtdata_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samgovtdata',
            name='fullParentPathCode',
            field=models.CharField(max_length=1000),
        ),
    ]
