# Generated by Django 4.1.5 on 2023-01-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_samgovtdata_fullparentpathcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samgovtdata',
            name='classificationCode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='fax',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='naicsCode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='noticeId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='solicitationNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='zipcode',
            field=models.CharField(max_length=255),
        ),
    ]
