# Generated by Django 4.1.5 on 2023-01-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_samgovtdata_classificationcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samgovtdata',
            name='active',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='award',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='classificationCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='countryCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='fax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='fullName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='fullParentPathCode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='fullParentPathName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='links',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='naicsCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='noticeId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='organizationType',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='solicitationNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='state',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='type',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='typeOfSetAside',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='typeOfSetAsideDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='uiLink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='samgovtdata',
            name='zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
